### ISSUE TITLE
Service Status - Publish messages on selected sections of the site

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_services#112]
Coming from https://miro.com/app/board/o9J_lHm9M2s=/?moveToWidget=3074457357810326500&cot=14 

## User story 

**As a** content designer

**I want** to publish a service status message within the content on selected pages of the site

**so that** I can notify citizens of a change to a specific service

----------

Difference between alert banners and service status messages

- Alert banners run across the top of all pages
- Service status messages are within the content of a page - see https://www.croydon.gov.uk/libraries-leisure-and-culture/libraries/find-your-library/ashburton-library as an example
- Service status messages allow you to read more - see https://www.brighton-hove.gov.uk/rubbish-recycling-and-streets

## Assumptions:

 - We will be using the existing service status content type.

--------------

## Acceptance tests

As a content designer, go to to 
/node/add/localgov_services_status

1. Add a service status message
    1. With content fields:
        1. Title (should this be "name" and not displayed in the pattern? ask andy)
        2. Service landing page: None
        3. Impact: Limited service
        4. Summary: (Plain text)
        5. Body: (Formatted text with links)
    2. Add a path that the alert should display (use same method as targeted alerts)
        3. (url alias of service page)
        4. (separate tests for each of the content formats?)
    3. Change state: Published
    4. Save
    5. Go to url alias above
    6. See service status message on the page. Styling should be "alert info" with the "i" icon
2. Update service status
    1. With content fields:
    2. Impact: Revised service
    3. Save
    4. See service status message on the page. Styling should be "alert warning/ danger" with the warning triangle icon
3. Update service status
    1. Change state: Archive
    2. Save
    3. Go to url alias above
    4. Service status message should be unpublished

--------------

Content formats

Add service status message to the following formats, above the body copy unless specified

As an MVP (so we can show to the targeted alerts working group):

Service page eg https://localgovdrupal.agile.coop/libraries-leisure-and-culture/z-sports-and-activities/basketball

Include in MVP depending on complexity/ estimates:

- Guide overview/ page
- Step by step overview/ page
- Directory channel, above the map
- Directory venue/ page

--------------

Leave the following fields in place for now

(Pick a) Service landing page
Show on landing page

My hunch is that these should be removed, and service landing pages can be targeted in the same way as other content formats, but we need to research Brighton's use of the service status pattern first

- Currently appears on service landing pages eg https://www.brighton-hove.gov.uk/rubbish-recycling-and-streets and seems buried here
- Would they prefer copy on every affected page, rather than just the landing page?
- What's the need for a public history of messages? Surely old messages about bins not being collected is confusing?

**Comment by willguv** [comment]
I wrote this on a duplicate card

We've discussed making changes to the way service status messages appear within services

## Currently

Content designers pick a service, and the status message is added to a block on the service landing page

See https://www.brighton-hove.gov.uk/rubbish-recycling-and-streets

<img width="1085" alt="Service message on a landing page" src="https://user-images.githubusercontent.com/708140/119350543-5fe72700-bc97-11eb-9b9d-0230773addb9.png">

We're planning to talk with the Brighton & Hove content team about the effectiveness of this pattern, so it should be left in place for now

## User needs/ evidence

As a content designer
I want to publish a service status message within the content on selected pages of the site
so that I can notify citizens of a change to a specific service

Evidence is limited, but feedback from @benhillsjones and others suggest a service status should be added to all related pages, and immediately beneath the page title and summary. Ben has tried this manually in Croydon with good results

<img width="1161" alt="Status message on service page" src="https://user-images.githubusercontent.com/708140/119349308-ee5aa900-bc95-11eb-91cb-c31275092cf7.png">

## Proposal

Modify the existing service status format

https://localgovdrupal.agile.coop/node/14/edit?destination=/admin/content%3Ftitle%3D%26type%3DAll%26status%3DAll%26langcode%3DAll%26page%3D1

- Impact field sets the status style. Suggest we follow the styles on https://localgovdrupal.agile.coop/service-status for consistency. Click the tabs to see alert-danger, alert-warning and alert-success classes

- Summary is shown in the service message. A "Read more" link takes users to any copy in the body

- Use the same page targeting method as alert banners for consistency

- Apply this to service pages only, initially so it can be shown to a wider group of content designers

**Comment by willguv** [comment]
@stephen-cox I can't find my previous feedback on this - are there 2 cards?

## Possible bug 

It doesn't seem like this change has been added to Guides

I tried adding /adult-health-and-social-care/travel-passes-and-support/blue-badges/* to https://test.localgov.agile.coop/node/69/edit?destination=/admin/content and the service status message does not appear on any pages in the guide

## Comments from @benhillsjones 

- There are times when there's no extra content for users to read. So should the Body field be optional? If there's no content, the "read more" link does not appear

- He asked if it's possible to offer a "open in new page" option? 

If unchecked, clicking "read more" shows the body content on the same page underneath the summary
If checked, clicking "read more" shows the body content on a new page (as now)

I'm happy to add a new card for this extra request so we can estimate and consider for a future sprint

**Comment by stephen-cox** [comment]
Hi @willguv - looks like there are 2 issues for this #112 and #113

> It doesn't seem like this change has been added to Guides

I have just edit the status [here](https://test.localgovdrupal.org/adult-health-and-social-care/status/service-operating-normal) and added the following rules

```
/adult-health-and-social-care/travel-passes-and-support/blue-badges
/adult-health-and-social-care/travel-passes-and-support/blue-badges/*
```

It looks to appear on some blue badge pages as expected:

- https://test.localgovdrupal.org/adult-health-and-social-care/travel-passes-and-support/blue-badges
- https://test.localgovdrupal.org/adult-health-and-social-care/travel-passes-and-support/blue-badges/blue-badge-fraud

It doesn't appear on others because there's an issue with the paths in the demo content. It's not on these because the URLs are not what they should be.

- https://test.localgovdrupal.org/blue-badges/apply-blue-badge
- https://test.localgovdrupal.org/travel-passes-and-support/blue-badges/blue-badges-organisations

I've created an issue for this in the demo content module; https://github.com/localgovdrupal/localgov_demo/issues/39

> Comments from @benhillsjones

At the moment it's not possible to have service status messages without a body. They are used in several places and the body is used in some of these. We would need to review the use of service statuses across the site, which looks likely to happen at some point.

It would be possible to implement the read more link so it either shows the body inline or takes you to the status message page, but I would suggest creating a new issue for this so it can be fully discussed before implementing it.
